version: '2'

services:
  productcatalogservice:
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
